#!/bin/bash
# Reproducible WSL/Linux build + test harness for the N-API migration.
#
# Portable: derives the repo path from this script, expects the toolchain in
# $HOME/toolchain (Node headers + extracted GDAL runtime/libs, see setup.sh).
#
# Usage:  .commandcode/wsl/run.sh build [syntax|full]
#         .commandcode/wsl/run.sh test [mocha args...]
set -e

HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO=$(cd "$HERE/../.." && pwd)
TC=${TC:-$HOME/toolchain}
WS=${WS:-$HOME/ws}
MODE=${1:-build}

export PATH="$TC/node/bin:$PATH"
_LIBDIRS=$(find "$TC/gdal-sys" -name '*.so*' -printf '%h\n' 2>/dev/null | sort -u | tr '\n' ':')
export LD_LIBRARY_PATH="${_LIBDIRS}${LD_LIBRARY_PATH}"

GDAL_INC="$TC/gdal-sys/usr/include/gdal"
GDAL_LIB="$TC/gdal-sys/usr/lib/x86_64-linux-gnu"
NODE_INC="$TC/node/include/node"

INCS="-I$NODE_INC -I$GDAL_INC -I$TC/gdal-sys/usr/include -I$WS/include -I$WS/src -I$WS/src/utils -I$WS/node_modules/nan -I$WS/node_modules/node-addon-api"
DEFS="-DNODE_GYP_MODULE_NAME=gdal -DBUILDING_NODE_EXTENSION -DPLATFORM=linux -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DNOGDI=1 -DHAVE_LIBZ=1 -DLINUX -DBUNDLED_GDAL=1"
FLAGS="-std=gnu++20 -fPIC -O1 -w -frtti -fexceptions"

# sync sources into the ext4 workspace (much faster than building on /mnt/c)
mkdir -p "$WS"
rsync -a --delete "$REPO/src/" "$WS/src/"
rsync -a --delete "$REPO/include/" "$WS/include/"
cp -f "$REPO/binding.gyp" "$REPO/package.json" "$REPO/tsconfig.json" "$WS/" 2>/dev/null || true
cp -f "$REPO/.mocharc.json" "$WS/" 2>/dev/null || true
cp -f "$REPO/CMakeLists.txt" "$WS/" 2>/dev/null || true
mkdir -p "$WS/obj"

SOURCES=$(grep -oE '"src/[^"]+\.cpp"' "$WS/binding.gyp" | tr -d '"')
echo "$SOURCES" | tr ' ' '\n' | grep . > "$WS/obj/sources.txt"

if [ "$MODE" = "syntax" ]; then
  FAIL=0
  while read -r s; do
    o="$WS/obj/$(echo "$s" | tr '/' '_' | sed 's/\.cpp$/.o/')"
    if ! g++ $FLAGS $DEFS $INCS -fsyntax-only "$WS/$s" 2> "$o.err"; then
      echo "FAIL: $s"; head -30 "$o.err"; FAIL=1
    fi
  done < "$WS/obj/sources.txt"
  [ $FAIL -eq 0 ] && echo "SYNTAX OK: $(wc -l < "$WS/obj/sources.txt") files"
  exit $FAIL
fi

if [ "$MODE" = "build" ]; then
  compile_one() {
    s="$1"
    o="$WS/obj/$(echo "$s" | tr '/' '_' | sed 's/\.cpp$/.o/')"
    g++ -c $FLAGS $DEFS $INCS -o "$o" "$WS/$s" 2> "$o.err" \
      || { echo "COMPILE FAIL: $s"; head -40 "$o.err"; return 1; }
  }
  export -f compile_one; export WS FLAGS DEFS INCS
  xargs -a "$WS/obj/sources.txt" -P "$(nproc)" -I{} bash -c 'compile_one "$@"' _ {}
  OBJS=$(sed 's#\.cpp$#.o#' "$WS/obj/sources.txt" | tr '/' '_' | sed "s#^#$WS/obj/#" | tr '\n' ' ')
  BINDIR="$WS/lib/binding/node-v137-linux-x64"
  mkdir -p "$BINDIR"
  g++ -shared -o "$BINDIR/gdal.node" $OBJS -L"$GDAL_LIB" -lgdal -Wl,-rpath,"$GDAL_LIB"
  echo "BUILD OK: $BINDIR/gdal.node"
  exit 0
fi

if [ "$MODE" = "test" ]; then
  # provision the "bundled" data layout lib/gdal.js expects
  mkdir -p "$WS/deps/libgdal/gdal/frmts/grib" "$WS/deps/libproj/proj"
  [ -d "$WS/deps/libgdal/gdal/data" ] || cp -r "$TC/gdal-sys/usr/share/gdal" "$WS/deps/libgdal/gdal/data"
  [ -d "$WS/deps/libproj/proj/data" ] || cp -r "$TC/gdal-sys/usr/share/proj" "$WS/deps/libproj/proj/data"
  cp -r "$REPO/deps/libgdal/gdal/frmts/grib/data" "$WS/deps/libgdal/gdal/frmts/grib/" 2>/dev/null || true
  cd "$WS"
  unset GDAL_DATA PROJ_LIB
  shift || true
  exec node_modules/.bin/mocha --reporter dot --timeout 20000 "$@"
fi

if [ "$MODE" = "cmakejs" ]; then
  [ -d "$WS/node_modules/node-addon-api" ] || { echo "missing node_modules/node-addon-api in $WS"; exit 1; }
  cd "$WS"
  # a build dir made by another generator cannot be reused, CMake refuses
  if [ -f "$WS/build/CMakeCache.txt" ] && ! grep -q '^CMAKE_GENERATOR:INTERNAL=Ninja' "$WS/build/CMakeCache.txt"; then
    echo "removing $WS/build (was not generated by Ninja)"
    rm -rf "$WS/build"
  fi
  # cmake-js parses these itself from argv and requires indexOf('=') >= 5, so the
  # key has to be glued to --CD: --CD<KEY>=<VALUE> becomes -D<KEY>=<VALUE>.
  cmake-js build \
    -G Ninja \
    --CDGDAL_INCLUDE_DIR="$GDAL_INC" \
    --CDGDAL_LIBRARY="$GDAL_LIB/libgdal.so"
  echo "CMAKE-JS BUILD OK"
  exit 0
fi

echo "usage: run.sh [build|syntax|cmakejs|test] [args]"
exit 1
