name: Publish prebuilt binaries

on: workflow_dispatch

jobs:
  publish_linux:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js 24.x
      uses: actions/setup-node@v6
      with:
        node-version: 24.x
    - uses: actions/setup-python@v6
      with:
        python-version: "3.11"
    - name: Setup Conan
      run: |
        pip install conan
        conan profile detect
    - name: Install Conan dependencies
      run: conan install . -of=conan/install --build=missing
    - run: npm install --ignore-scripts
    - name: Build
      run: npx cmake-js compile -j max
      env:
        CMAKE_TOOLCHAIN_FILE: conan/install/conan_toolchain.cmake
    - run: npm test
    - name: Package binary
      run: npx @mapbox/node-pre-gyp package
    - name: Publish to GitHub Release
      run: |
        VERSION=$(node -p "require('./package.json').version")
        gh release upload "v$VERSION" build/stage/**/*.tar.gz --clobber
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_macos:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js 24.x
      uses: actions/setup-node@v6
      with:
        node-version: 24.x
    - uses: actions/setup-python@v6
      with:
        python-version: "3.11"
    - name: Setup Conan
      run: |
        pip install conan
        conan profile detect
    - name: Install Conan dependencies
      run: conan install . -of=conan/install --build=missing
    - run: npm install --ignore-scripts
    - name: Build
      run: npx cmake-js compile -j max
      env:
        CMAKE_TOOLCHAIN_FILE: conan/install/conan_toolchain.cmake
    - run: npm test
    - name: Package binary
      run: npx @mapbox/node-pre-gyp package
    - name: Publish to GitHub Release
      run: |
        VERSION=$(node -p "require('./package.json').version")
        gh release upload "v$VERSION" build/stage/**/*.tar.gz --clobber
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_windows:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js 24.x
      uses: actions/setup-node@v6
      with:
        node-version: 24.x
    - uses: actions/setup-python@v6
      with:
        python-version: "3.11"
    - name: Setup Conan
      run: |
        pip install conan
        conan profile detect
    - name: Install Conan dependencies
      run: conan install . -of=conan/install --build=missing
    - run: npm install --ignore-scripts
    - name: Build
      run: npx cmake-js compile -j max
      env:
        CMAKE_TOOLCHAIN_FILE: conan/install/conan_toolchain.cmake
    - run: npm test
    - name: Package binary
      run: npx @mapbox/node-pre-gyp package
    - name: Publish to GitHub Release
      run: |
        $VERSION = (node -p "require('./package.json').version")
        gh release upload "v$VERSION" build/stage/**/*.tar.gz --clobber
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
