name: Test npm package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version to test'
        required: true

jobs:
  test_npm_binaries:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-24.04, windows-2022, macos-15 ]

    steps:
    - name: Use Node.js 24.x
      uses: actions/setup-node@v6
      with:
        node-version: 24.x
    - uses: actions/setup-python@v6
      with:
        python-version: "3.11"
    - uses: actions/checkout@v6
    - run: npm install
    - name: Install from npm
      run: npm install --force @yjdyamv/gdal-async@${{ github.event.inputs.version }}
    - name: Run unit tests
      run: |
        cd test
        npx tsc -p tsconfig.test.json --noEmit
        npx mocha --v8-expose-gc --reporter=tap -r tsx -r _common.ts -r _hooks.ts --timeout 20000 *.test.ts

  test_npm_rebuild:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-24.04, windows-2022, macos-15 ]

    steps:
    - name: Use Node.js 24.x
      uses: actions/setup-node@v6
      with:
        node-version: 24.x
    - uses: actions/setup-python@v6
      with:
        python-version: "3.11"
    - uses: actions/checkout@v6
    - run: npm install
    - name: Rebuild from source
      run: npm install --verbose --force @yjdyamv/gdal-async@${{ github.event.inputs.version }} --build-from-source
    - name: Run unit tests
      run: |
        cd test
        npx tsc -p tsconfig.test.json --noEmit
        npx mocha --v8-expose-gc --reporter=tap -r tsx -r _common.ts -r _hooks.ts --timeout 20000 *.test.ts
