name: Test release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test_linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linux-version:
          - ubuntu:22.04
          - ubuntu:24.04
          - debian:bookworm
          - fedora:42
          - amazonlinux:2023

    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js 24.x
      uses: actions/setup-node@v6
      with:
        node-version: 24.x
    - run: npm run container release ${{ matrix.linux-version }} 24
      env:
        MOCHA_TEST_NETWORK: 1

  test_macos:
    runs-on: ${{ matrix.macos-version }}
    strategy:
      fail-fast: false
      matrix:
        macos-version: [ macos-14, macos-15 ]

    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js 24.x
      uses: actions/setup-node@v6
      with:
        node-version: 24.x
    - uses: actions/setup-python@v6
      with:
        python-version: "3.11"
    - name: Setup Conan
      run: |
        pip install conan
        conan profile detect
    - name: Install Conan dependencies
      run: conan install . -of=conan/install --build=missing
    - run: npm install --ignore-scripts
    - name: Build
      run: npx cmake-js compile -j max
      env:
        CMAKE_TOOLCHAIN_FILE: conan/install/conan_toolchain.cmake
    - run: npm test
      env:
        MOCHA_TEST_NETWORK: 1

  test_windows:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js 24.x
      uses: actions/setup-node@v6
      with:
        node-version: 24.x
    - uses: actions/setup-python@v6
      with:
        python-version: "3.11"
    - name: Setup Conan
      run: |
        pip install conan
        conan profile detect
    - name: Install Conan dependencies
      run: conan install . -of=conan/install --build=missing
    - run: npm install --ignore-scripts
    - name: Build
      run: npx cmake-js compile -j max
      env:
        CMAKE_TOOLCHAIN_FILE: conan/install/conan_toolchain.cmake
    - run: npm test
      env:
        MOCHA_TEST_NETWORK: 1
