name: Node.js CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test_linux:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js 24.x
      uses: actions/setup-node@v6
      with:
        node-version: 24.x
    - name: Install system deps
      run: sudo apt-get install -y build-essential autoconf autoconf-archive automake libtool ninja-build
    - name: Get vcpkg baseline
      id: baseline
      run: echo "value=$(node -p "require('./vcpkg.json')['builtin-baseline']")" >> "$GITHUB_OUTPUT"
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: ${{ steps.baseline.outputs.value }}
    - run: npm install --ignore-scripts
    - name: Build
      run: npx cmake-js compile -j max --CDCMAKE_TOOLCHAIN_FILE="$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"
    - name: Run tests
      run: npm test
      env:
        MOCHA_TEST_NETWORK: 1

  test_macos:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js 24.x
      uses: actions/setup-node@v6
      with:
        node-version: 24.x
    - name: Install system deps
      run: brew install autoconf automake libtool ninja
    - name: Get vcpkg baseline
      id: baseline
      run: echo "value=$(node -p "require('./vcpkg.json')['builtin-baseline']")" >> "$GITHUB_OUTPUT"
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: ${{ steps.baseline.outputs.value }}
    - run: npm install --ignore-scripts
    - name: Build
      run: npx cmake-js compile -j max --CDCMAKE_TOOLCHAIN_FILE="$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"
    - name: Run tests
      run: npm test
      env:
        MOCHA_TEST_NETWORK: 1

  test_windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js 24.x
      uses: actions/setup-node@v6
      with:
        node-version: 24.x
    - name: Get vcpkg baseline
      id: baseline
      shell: pwsh
      run: |
        $v = (node -p "require('./vcpkg.json')['builtin-baseline']")
        "value=$v" >> $env:GITHUB_OUTPUT
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: ${{ steps.baseline.outputs.value }}
    - run: npm install --ignore-scripts
    - name: Build
      shell: pwsh
      run: npx cmake-js compile -j max --CDCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT\scripts\buildsystems\vcpkg.cmake"
    - name: Run tests
      run: npm test
      env:
        MOCHA_TEST_NETWORK: 1
